import { Task } from "@/types/task";

export const getTasks: Task[] = [
  {
    id: 1,
    title: "Design Landing Page",
    description: "Create a responsive landing page for the marketing campaign.",
    dueDate: new Date(Date.now() + 1 * 86400000).toISOString(),
    status: "In Progress",
    priority: "High",
  },
  {
    id: 2,
    title: "Fix Login Bug",
    description: "Users are unable to login when using Safari browser.",
    dueDate: new Date(Date.now() + 2 * 86400000).toISOString(),
    status: "In Progress",
    priority: "High",
  },
  {
    id: 3,
    title: "Optimize Database",
    description: "Improve query performance and reduce DB load.",
    dueDate: new Date(Date.now() + 3 * 86400000).toISOString(),
    status: "Completed",
    priority: "Medium",
  },
  {
    id: 4,
    title: "Team Meeting",
    description: "Weekly sync-up meeting for project updates.",
    dueDate: new Date(Date.now() + 4 * 86400000).toISOString(),
    status: "Completed",
    priority: "Low",
  },
  {
    id: 5,
    title: "Write Unit Tests",
    description: "Increase test coverage for core modules.",
    dueDate: new Date(Date.now() + 5 * 86400000).toISOString(),
    status: "In Progress",
    priority: "Medium",
  },
  {
    id: 6,
    title: "Deploy API v2",
    description: "Rollout API version 2 to production environment.",
    dueDate: new Date(Date.now() + 6 * 86400000).toISOString(),
    status: "In Progress",
    priority: "High",
  },
  {
    id: 7,
    title: "Client Feedback",
    description: "Collect feedback from client after demo.",
    dueDate: new Date(Date.now() + 7 * 86400000).toISOString(),
    status: "Completed",
    priority: "Low",
  },
  {
    id: 8,
    title: "Create Marketing Plan",
    description: "Prepare a 3-month digital marketing strategy.",
    dueDate: new Date(Date.now() + 8 * 86400000).toISOString(),
    status: "In Progress",
    priority: "Medium",
  },
  {
    id: 9,
    title: "Onboard New Developer",
    description: "Setup onboarding process for new hires.",
    dueDate: new Date(Date.now() + 9 * 86400000).toISOString(),
    status: "Completed",
    priority: "Low",
  },
  {
    id: 10,
    title: "Research Competitors",
    description: "Study competitor features and market positioning.",
    dueDate: new Date(Date.now() + 10 * 86400000).toISOString(),
    status: "In Progress",
    priority: "Medium",
  },
];
